get around splunk accept license issues

diff --git a/deploy/sidecar/Dockerfile b/deploy/sidecar/Dockerfile
--- a/deploy/sidecar/Dockerfile
+++ b/deploy/sidecar/Dockerfile
@@ -5,29 +5,45 @@ WORKDIR /home/runner
 RUN apt-get update
 RUN apt-get install curl procps unzip -y
 
-RUN if [ "$(dpkg --print-architecture)" = "arm64" ]; then \
+ARG TARGETPLATFORM
+ENV SPLUNK_HOME=/opt/splunkforwarder
+
+# Download and install Splunk Universal Forwarder & AWS CLI
+# Uses the targetplatform to get the correct architecture
+RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
       curl "https://download.splunk.com/products/universalforwarder/releases/9.1.3/linux/splunkforwarder-9.1.3-d95b3299fa65-Linux-armv8.tgz" -o "splunkforwarder-9.1.3-d95b3299fa65-Linux-armv8.tgz"; \
       tar xvfz splunkforwarder-9.1.3-d95b3299fa65-Linux-armv8.tgz -C /opt; \
       curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscli.zip"; \
-    elif [ "$(dpkg --print-architecture)" = "amd64" ]; then \
+    elif [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
       curl "https://download.splunk.com/products/universalforwarder/releases/9.1.3/linux/splunkforwarder-9.1.3-d95b3299fa65-Linux-x86_64.tgz" -o "splunkforwarder-9.1.3-d95b3299fa65-Linux-x86_64.tgz"; \
       tar xvfz splunkforwarder-9.1.3-d95b3299fa65-Linux-x86_64.tgz -C /opt; \
       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli.zip"; \
     else \
-      echo "Architecture $(dpkg --print-architecture) is not supported."; exit 1; \
+      echo "Architecture $TARGETPLATFORM is not supported."; exit 1; \
     fi
 
 COPY deploy/sidecar/ /home/runner/deploy/sidecar
 
-RUN mv ./deploy/sidecar/splunk/inputs.conf /opt/splunkforwarder/etc/system/local/inputs.conf
-RUN mv ./deploy/sidecar/splunk/user-seed.conf /opt/splunkforwarder/etc/system/local/user-seed.conf
+# Copy the configuration files to the correct location
+RUN mv ./deploy/sidecar/splunk/inputs.conf ${SPLUNK_HOME}/etc/system/local/inputs.conf
+RUN mv ./deploy/sidecar/splunk/user-seed.conf ${SPLUNK_HOME}/etc/system/local/user-seed.conf
 
+# Get around the fact that the UF --accept-license flag doesn't work without a tty
+RUN rm ${SPLUNK_HOME}/ftr
+
+# Install the AWS CLI
 RUN unzip awscli.zip
 RUN ./aws/install
 RUN /usr/local/bin/aws --version
 
+# Copy the entrypoint script and make it executable
 RUN mv ./deploy/sidecar/entrypoint /home/runner/entrypoint
 RUN chmod +x /home/runner/entrypoint
+
+# Clean up
+RUN rm -rf ./*.tgz
+RUN rm -rf ./*.zip
+RUN rm -rf ./deploy/sidecar
 
 EXPOSE 8125
 
